-- Moda Juárez: autenticación, catálogo, inventario y Storage.
-- Ejecutar únicamente en el proyecto NUEVO de Supabase para Moda Juárez.
-- Es idempotente: puede ejecutarse nuevamente sin borrar el catálogo.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id,email,role)
  values(new.id,new.email,'customer')
  on conflict (id) do update set email=excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id=auth.uid() and role='admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.shop_products (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  name text not null,
  category text not null default 'Sin categoría',
  description text,
  price numeric(12,2) not null default 0 check (price >= 0),
  compare_at_price numeric(12,2) check (compare_at_price is null or compare_at_price >= 0),
  currency char(3) not null default 'MXN',
  image_1 text,
  image_2 text,
  image_3 text,
  badge text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.shop_products(id) on delete cascade,
  variant_sku text not null unique,
  size text not null default 'UNITALLA',
  color text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.shop_inventory (
  variant_id bigint primary key references public.shop_product_variants(id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.shop_inventory_movements (
  id bigint generated by default as identity primary key,
  variant_id bigint not null references public.shop_product_variants(id) on delete cascade,
  movement_type text not null,
  quantity integer not null,
  previous_stock integer not null,
  new_stock integer not null check (new_stock >= 0),
  reason text,
  reference text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists idx_shop_products_active_category
  on public.shop_products(active,category);
create index if not exists idx_shop_variants_product
  on public.shop_product_variants(product_id);
create index if not exists idx_shop_movements_variant_created
  on public.shop_inventory_movements(variant_id,created_at desc);

alter table public.profiles enable row level security;
alter table public.shop_products enable row level security;
alter table public.shop_product_variants enable row level security;
alter table public.shop_inventory enable row level security;
alter table public.shop_inventory_movements enable row level security;

drop policy if exists profiles_read_own_or_admin on public.profiles;
create policy profiles_read_own_or_admin on public.profiles
for select to authenticated
using (id=auth.uid() or (select public.is_admin()));

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists products_public_read on public.shop_products;
create policy products_public_read on public.shop_products
for select to anon,authenticated
using (active or (select public.is_admin()));

drop policy if exists products_admin_all on public.shop_products;
create policy products_admin_all on public.shop_products
for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists variants_public_read on public.shop_product_variants;
create policy variants_public_read on public.shop_product_variants
for select to anon,authenticated
using (
  active and exists(
    select 1 from public.shop_products p
    where p.id=product_id and p.active
  )
  or (select public.is_admin())
);

drop policy if exists variants_admin_all on public.shop_product_variants;
create policy variants_admin_all on public.shop_product_variants
for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists inventory_public_read on public.shop_inventory;
create policy inventory_public_read on public.shop_inventory
for select to anon,authenticated
using (
  exists(
    select 1
    from public.shop_product_variants v
    join public.shop_products p on p.id=v.product_id
    where v.id=variant_id and v.active and p.active
  )
  or (select public.is_admin())
);

drop policy if exists inventory_admin_all on public.shop_inventory;
create policy inventory_admin_all on public.shop_inventory
for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists movements_admin_all on public.shop_inventory_movements;
create policy movements_admin_all on public.shop_inventory_movements
for all to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values(
  'productos','productos',true,5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists product_images_public_read on storage.objects;
create policy product_images_public_read on storage.objects
for select to public
using (bucket_id='productos');

drop policy if exists product_images_admin_insert on storage.objects;
create policy product_images_admin_insert on storage.objects
for insert to authenticated
with check (bucket_id='productos' and (select public.is_admin()));

drop policy if exists product_images_admin_update on storage.objects;
create policy product_images_admin_update on storage.objects
for update to authenticated
using (bucket_id='productos' and (select public.is_admin()))
with check (bucket_id='productos' and (select public.is_admin()));

drop policy if exists product_images_admin_delete on storage.objects;
create policy product_images_admin_delete on storage.objects
for delete to authenticated
using (bucket_id='productos' and (select public.is_admin()));

