-- Moda Juárez Bot: tablas privadas y permanentes.
-- Sin políticas públicas: no quedan expuestas mediante la publishable key.

create table if not exists public.bot_products (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  name text not null,
  price numeric(12,2) not null check (price > 0),
  stock integer not null default 0 check (stock >= 0),
  sizes text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.bot_posts (
  id bigint generated by default as identity primary key,
  platform text not null,
  status text not null default 'draft',
  title text not null default '',
  caption text not null,
  media_url text not null default '',
  scheduled_at timestamptz,
  external_id text not null default '',
  error text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.bot_leads (
  id bigint generated by default as identity primary key,
  source text not null,
  name text not null default '',
  contact text not null default '',
  message text not null default '',
  intent text not null default 'unknown',
  status text not null default 'new',
  attribution jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.bot_sales (
  id bigint generated by default as identity primary key,
  product_id bigint references public.bot_products(id) on delete set null,
  qty integer not null check (qty > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  channel text not null default '',
  customer text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.bot_settings (
  key text primary key,
  value text not null
);

create table if not exists public.bot_marketing_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_name text not null,
  source_url text not null default '',
  product_sku text not null default '',
  value numeric(12,2),
  currency char(3) not null default 'MXN',
  attribution jsonb not null default '{}'::jsonb,
  custom_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_bot_events_name_created
  on public.bot_marketing_events(event_name,created_at desc);
create index if not exists idx_bot_leads_status_created
  on public.bot_leads(status,created_at desc);
create index if not exists idx_bot_posts_status_scheduled
  on public.bot_posts(status,scheduled_at);

alter table public.bot_products enable row level security;
alter table public.bot_posts enable row level security;
alter table public.bot_leads enable row level security;
alter table public.bot_sales enable row level security;
alter table public.bot_settings enable row level security;
alter table public.bot_marketing_events enable row level security;

