-- WOMAN 656: libro contable operativo configurable.
-- Ejecutar después de 006_accounting_and_pricing.sql.
-- No emite CFDI ni presenta declaraciones ante el SAT.

alter table public.pricing_settings
  add column if not exists sales_tax_rate numeric(6,3) not null default 16,
  add column if not exists income_tax_rate numeric(6,3) not null default 0,
  add column if not exists fiscal_regime text not null default 'PLATAFORMAS_TECNOLOGICAS',
  add column if not exists border_stimulus_enabled boolean not null default false,
  add column if not exists platform_isr_withholding_rate numeric(6,3) not null default 0,
  add column if not exists platform_vat_withholding_rate numeric(6,3) not null default 0;

update public.pricing_settings
set default_tax_rate=16, sales_tax_rate=16
where id=1;

create table if not exists public.accounting_accounts (
  code text primary key,
  name text not null,
  account_type text not null check (account_type in ('asset','liability','equity','income','cost','expense')),
  normal_balance text not null check (normal_balance in ('debit','credit')),
  active boolean not null default true
);

insert into public.accounting_accounts(code,name,account_type,normal_balance) values
('101-01','Caja y bancos','asset','debit'),
('105-01','Clientes','asset','debit'),
('115-01','Inventario de mercancías','asset','debit'),
('118-01','IVA acreditable','asset','debit'),
('119-01','IVA a favor','asset','debit'),
('201-01','Proveedores','liability','credit'),
('208-01','IVA trasladado','liability','credit'),
('209-01','IVA por pagar','liability','credit'),
('210-01','ISR retenido por plataformas','asset','debit'),
('210-02','IVA retenido por plataformas','asset','debit'),
('301-01','Capital','equity','credit'),
('401-01','Ventas directas','income','credit'),
('401-02','Ventas por plataformas','income','credit'),
('402-01','Devoluciones sobre ventas','income','debit'),
('501-01','Costo de ventas','cost','debit'),
('601-01','Gastos de envío','expense','debit'),
('601-02','Gastos de importación','expense','debit'),
('601-03','Comisiones de plataformas','expense','debit'),
('601-99','Otros gastos','expense','debit')
on conflict (code) do update set name=excluded.name, account_type=excluded.account_type, normal_balance=excluded.normal_balance;

create table if not exists public.accounting_transactions (
  id uuid primary key default gen_random_uuid(),
  operation_date date not null default current_date,
  operation_type text not null check (operation_type in ('sale','return','purchase','expense','adjustment','opening')),
  channel text not null default 'direct' check (channel in ('direct','platform')),
  reference text,
  customer_or_supplier text,
  subtotal numeric(14,2) not null default 0,
  tax_rate numeric(6,3) not null default 16,
  tax_amount numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  cost_amount numeric(14,2) not null default 0,
  platform_fee numeric(14,2) not null default 0,
  isr_withheld numeric(14,2) not null default 0,
  vat_withheld numeric(14,2) not null default 0,
  payment_method text not null default 'bank',
  notes text,
  status text not null default 'posted' check (status in ('draft','posted','cancelled')),
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.accounting_entries (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid references public.accounting_transactions(id) on delete cascade,
  entry_date date not null default current_date,
  entry_number bigint generated by default as identity unique,
  concept text not null,
  status text not null default 'posted' check (status in ('draft','posted','cancelled')),
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.accounting_entry_lines (
  id bigint generated by default as identity primary key,
  entry_id uuid not null references public.accounting_entries(id) on delete cascade,
  account_code text not null references public.accounting_accounts(code),
  description text,
  debit numeric(14,2) not null default 0 check (debit>=0),
  credit numeric(14,2) not null default 0 check (credit>=0),
  check ((debit>0 and credit=0) or (credit>0 and debit=0))
);

create or replace function public.post_accounting_transaction(p_transaction uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare t public.accounting_transactions%rowtype; e uuid; cash_amount numeric(14,2);
begin
  if not public.is_admin() then raise exception 'Solo ADMIN puede generar pólizas'; end if;
  select * into t from public.accounting_transactions where id=p_transaction and status='posted';
  if not found then raise exception 'Operación inexistente o no contabilizable'; end if;
  if exists(select 1 from public.accounting_entries where transaction_id=t.id and status='posted') then
    select id into e from public.accounting_entries where transaction_id=t.id and status='posted' limit 1; return e;
  end if;
  insert into public.accounting_entries(transaction_id,entry_date,concept)
  values(t.id,t.operation_date,upper(t.operation_type)||' · '||coalesce(t.reference,'sin referencia')) returning id into e;
  if t.operation_type='sale' then
    cash_amount:=t.total-t.platform_fee-t.isr_withheld-t.vat_withheld;
    if cash_amount>0 then insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'101-01','Cobro neto',cash_amount); end if;
    if t.platform_fee>0 then insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'601-03','Comisión plataforma',t.platform_fee); end if;
    if t.isr_withheld>0 then insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'210-01','ISR retenido por plataforma',t.isr_withheld); end if;
    if t.vat_withheld>0 then insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'210-02','IVA retenido por plataforma',t.vat_withheld); end if;
    insert into public.accounting_entry_lines(entry_id,account_code,description,credit) values(e,case when t.channel='platform' then '401-02' else '401-01' end,'Venta antes de IVA',t.subtotal);
    if t.tax_amount>0 then insert into public.accounting_entry_lines(entry_id,account_code,description,credit) values(e,'208-01','IVA trasladado',t.tax_amount); end if;
    if t.cost_amount>0 then
      insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'501-01','Costo de venta',t.cost_amount);
      insert into public.accounting_entry_lines(entry_id,account_code,description,credit) values(e,'115-01','Salida de inventario',t.cost_amount);
    end if;
  elsif t.operation_type='return' then
    insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'402-01','Devolución',t.subtotal);
    if t.tax_amount>0 then insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'208-01','Reversa IVA trasladado',t.tax_amount); end if;
    insert into public.accounting_entry_lines(entry_id,account_code,description,credit) values(e,'101-01','Reembolso',t.total);
    if t.cost_amount>0 then
      insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'115-01','Reingreso inventario',t.cost_amount);
      insert into public.accounting_entry_lines(entry_id,account_code,description,credit) values(e,'501-01','Reversa costo',t.cost_amount);
    end if;
  elsif t.operation_type in ('expense','purchase') then
    insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,case when t.operation_type='purchase' then '115-01' else '601-99' end,'Base',t.subtotal);
    if t.tax_amount>0 then insert into public.accounting_entry_lines(entry_id,account_code,description,debit) values(e,'118-01','IVA acreditable',t.tax_amount); end if;
    insert into public.accounting_entry_lines(entry_id,account_code,description,credit) values(e,'101-01','Pago',t.total);
  else
    raise exception 'Tipo aún no automatizado: %',t.operation_type;
  end if;
  return e;
end $$;

create or replace view public.accounting_trial_balance as
select a.code,a.name,a.account_type,a.normal_balance,
       coalesce(sum(case when e.status='posted' then l.debit else 0 end),0)::numeric(14,2) debit,
       coalesce(sum(case when e.status='posted' then l.credit else 0 end),0)::numeric(14,2) credit,
       (coalesce(sum(case when e.status='posted' then l.debit else 0 end),0)-coalesce(sum(case when e.status='posted' then l.credit else 0 end),0))::numeric(14,2) balance
from public.accounting_accounts a left join public.accounting_entry_lines l on l.account_code=a.code left join public.accounting_entries e on e.id=l.entry_id
group by a.code,a.name,a.account_type,a.normal_balance;

alter table public.accounting_accounts enable row level security;
alter table public.accounting_transactions enable row level security;
alter table public.accounting_entries enable row level security;
alter table public.accounting_entry_lines enable row level security;
grant select,insert,update,delete on public.accounting_accounts,public.accounting_transactions,public.accounting_entries,public.accounting_entry_lines to authenticated;
grant select on public.accounting_trial_balance to authenticated;
grant execute on function public.post_accounting_transaction(uuid) to authenticated;

do $$ declare tbl text; begin
  foreach tbl in array array['accounting_accounts','accounting_transactions','accounting_entries','accounting_entry_lines'] loop
    execute format('drop policy if exists %I on public.%I',tbl||'_admin_all',tbl);
    execute format('create policy %I on public.%I for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))',tbl||'_admin_all',tbl);
  end loop;
end $$;
