-- WOMAN 656 · perfiles de clientes, consentimiento y analítica comercial
-- La base productiva recibió esta migración el 2026-09-03.

alter table public.profiles
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists contact_email text,
  add column if not exists phone text,
  add column if not exists age smallint,
  add column if not exists auth_provider text not null default 'email',
  add column if not exists phone_verified boolean not null default false,
  add column if not exists marketing_consent boolean not null default false,
  add column if not exists marketing_consent_at timestamptz,
  add column if not exists profile_completed_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

alter table public.profiles drop constraint if exists profiles_age_check;
alter table public.profiles add constraint profiles_age_check check (age is null or age between 13 and 80);

create table if not exists public.store_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  visitor_id text not null,
  session_id text,
  user_id uuid references auth.users(id) on delete set null,
  product_id bigint references public.shop_products(id) on delete set null,
  product_sku text,
  occurred_at timestamptz not null default now(),
  event_date date not null default (timezone('America/Ciudad_Juarez',now()))::date,
  metadata jsonb not null default '{}'::jsonb,
  constraint store_analytics_event_name_check check (event_name in ('store_visit','product_view','add_to_cart','begin_checkout')),
  constraint store_analytics_visitor_check check (char_length(visitor_id) between 8 and 100)
);
create index if not exists store_analytics_events_date_idx on public.store_analytics_events(event_date desc);
create index if not exists store_analytics_events_user_idx on public.store_analytics_events(user_id,occurred_at desc);
create index if not exists store_analytics_events_product_idx on public.store_analytics_events(product_sku,occurred_at desc);
create unique index if not exists store_visit_user_daily_uq on public.store_analytics_events(event_date,user_id,event_name) where event_name='store_visit' and user_id is not null;
create unique index if not exists store_visit_visitor_daily_uq on public.store_analytics_events(event_date,visitor_id,event_name) where event_name='store_visit' and user_id is null;
create unique index if not exists product_view_user_daily_uq on public.store_analytics_events(event_date,user_id,product_sku,event_name) where event_name='product_view' and user_id is not null and product_sku is not null;
create unique index if not exists product_view_visitor_daily_uq on public.store_analytics_events(event_date,visitor_id,product_sku,event_name) where event_name='product_view' and user_id is null and product_sku is not null;

create table if not exists public.product_likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.shop_products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,product_id)
);
create index if not exists product_likes_product_idx on public.product_likes(product_id,created_at desc);

create table if not exists public.marketing_consent_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  consent boolean not null,
  source text not null default 'profile',
  created_at timestamptz not null default now()
);
create index if not exists marketing_consent_log_user_idx on public.marketing_consent_log(user_id,created_at desc);

create table if not exists public.marketing_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  email_normalized text generated always as (lower(btrim(email))) stored,
  active boolean not null default true,
  adult_confirmed boolean not null default false,
  source text not null default 'newsletter',
  consent_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  unique(email_normalized)
);

alter table public.store_analytics_events enable row level security;
alter table public.product_likes enable row level security;
alter table public.marketing_consent_log enable row level security;
alter table public.marketing_subscribers enable row level security;

-- El cliente NO recibe UPDATE directo a profiles para evitar que pueda cambiar role.
drop policy if exists profiles_update_own on public.profiles;

drop policy if exists analytics_admin_read on public.store_analytics_events;
create policy analytics_admin_read on public.store_analytics_events for select to authenticated using ((select public.is_admin()));
drop policy if exists product_likes_read_own_or_admin on public.product_likes;
create policy product_likes_read_own_or_admin on public.product_likes for select to authenticated using (user_id=auth.uid() or (select public.is_admin()));
drop policy if exists consent_log_read_own_or_admin on public.marketing_consent_log;
create policy consent_log_read_own_or_admin on public.marketing_consent_log for select to authenticated using (user_id=auth.uid() or (select public.is_admin()));
drop policy if exists subscribers_admin_read on public.marketing_subscribers;
create policy subscribers_admin_read on public.marketing_subscribers for select to authenticated using ((select public.is_admin()));

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_age smallint; v_marketing boolean:=false; v_first text; v_last text; v_phone text; v_provider text;
begin
  if coalesce(new.raw_user_meta_data->>'age','') ~ '^\d{1,3}$' then v_age:=(new.raw_user_meta_data->>'age')::smallint; if v_age<13 or v_age>80 then v_age:=null; end if; end if;
  v_first:=coalesce(nullif(new.raw_user_meta_data->>'first_name',''),nullif(new.raw_user_meta_data->>'given_name',''));
  v_last:=coalesce(nullif(new.raw_user_meta_data->>'last_name',''),nullif(new.raw_user_meta_data->>'family_name',''));
  v_phone:=nullif(new.raw_user_meta_data->>'phone','');
  v_provider:=coalesce(nullif(new.raw_app_meta_data->>'provider',''),'email');
  v_marketing:=lower(coalesce(new.raw_user_meta_data->>'marketing_consent','false')) in ('true','1','yes','si','sí') and coalesce(v_age,18)>=18;
  insert into public.profiles(id,email,contact_email,role,first_name,last_name,phone,age,auth_provider,marketing_consent,marketing_consent_at,profile_completed_at,last_seen,updated_at)
  values(new.id,new.email,new.email,'customer',v_first,v_last,v_phone,v_age,v_provider,v_marketing,case when v_marketing then now() end,case when v_first is not null and v_last is not null and new.email is not null and v_phone is not null and v_age is not null then now() end,now(),now())
  on conflict(id) do update set email=excluded.email,contact_email=coalesce(public.profiles.contact_email,excluded.contact_email),auth_provider=coalesce(nullif(public.profiles.auth_provider,''),excluded.auth_provider),first_name=coalesce(public.profiles.first_name,excluded.first_name),last_name=coalesce(public.profiles.last_name,excluded.last_name),updated_at=now();
  return new;
end; $$;

create or replace function public.record_store_event(p_event_name text,p_visitor_id text,p_session_id text default null,p_product_sku text default null,p_metadata jsonb default '{}'::jsonb)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_product_id bigint; v_metadata jsonb:=coalesce(p_metadata,'{}'::jsonb);
begin
  if p_event_name not in ('store_visit','product_view','add_to_cart','begin_checkout') then raise exception 'Evento no permitido'; end if;
  if p_visitor_id is null or char_length(p_visitor_id)<8 or char_length(p_visitor_id)>100 then raise exception 'Visitante inválido'; end if;
  if pg_column_size(v_metadata)>8192 then raise exception 'Metadata demasiado grande'; end if;
  if p_product_sku is not null then select id into v_product_id from public.shop_products where sku=p_product_sku limit 1; end if;
  begin insert into public.store_analytics_events(event_name,visitor_id,session_id,user_id,product_id,product_sku,metadata) values(p_event_name,p_visitor_id,p_session_id,v_uid,v_product_id,p_product_sku,v_metadata);
  exception when unique_violation then if v_uid is not null then update public.profiles set last_seen=now(),updated_at=now() where id=v_uid; end if; return false; end;
  if v_uid is not null then update public.profiles set last_seen=now(),updated_at=now() where id=v_uid; end if; return true;
end; $$;

create or replace function public.set_my_profile(p_first_name text,p_last_name text,p_contact_email text,p_phone text,p_age smallint,p_marketing_consent boolean default false)
returns public.profiles language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_previous boolean; v_effective boolean; v_row public.profiles;
begin
  if v_uid is null then raise exception 'Debes iniciar sesión'; end if;
  if nullif(btrim(p_first_name),'') is null or char_length(btrim(p_first_name))>80 then raise exception 'Nombre inválido'; end if;
  if nullif(btrim(p_last_name),'') is null or char_length(btrim(p_last_name))>120 then raise exception 'Apellido inválido'; end if;
  if p_contact_email is null or p_contact_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then raise exception 'Correo inválido'; end if;
  if nullif(btrim(p_phone),'') is null or char_length(btrim(p_phone))>30 then raise exception 'Teléfono inválido'; end if;
  if p_age is null or p_age<13 or p_age>80 then raise exception 'Edad fuera de rango'; end if;
  select marketing_consent into v_previous from public.profiles where id=v_uid; v_effective:=coalesce(p_marketing_consent,false) and p_age>=18;
  update public.profiles set first_name=btrim(p_first_name),last_name=btrim(p_last_name),contact_email=lower(btrim(p_contact_email)),phone=btrim(p_phone),age=p_age,marketing_consent=v_effective,marketing_consent_at=case when v_effective then coalesce(marketing_consent_at,now()) end,profile_completed_at=coalesce(profile_completed_at,now()),last_seen=now(),updated_at=now() where id=v_uid returning * into v_row;
  if v_previous is distinct from v_effective then insert into public.marketing_consent_log(user_id,consent,source) values(v_uid,v_effective,'profile'); end if; return v_row;
end; $$;

create or replace function public.toggle_product_like(p_product_sku text,p_like boolean)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_product_id bigint;
begin
  if v_uid is null then raise exception 'Debes iniciar sesión'; end if;
  select id into v_product_id from public.shop_products where sku=p_product_sku and active=true limit 1;
  if v_product_id is null then raise exception 'Producto no encontrado'; end if;
  if p_like then insert into public.product_likes(user_id,product_id) values(v_uid,v_product_id) on conflict do nothing; return true; end if;
  delete from public.product_likes where user_id=v_uid and product_id=v_product_id; return false;
end; $$;

create or replace function public.subscribe_marketing(p_email text,p_adult_confirmed boolean,p_source text default 'newsletter')
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if p_email is null or p_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then raise exception 'Correo inválido'; end if;
  if coalesce(p_adult_confirmed,false) is not true then raise exception 'La suscripción de ofertas requiere confirmar mayoría de edad'; end if;
  insert into public.marketing_subscribers(email,active,adult_confirmed,source,consent_at,unsubscribed_at) values(lower(btrim(p_email)),true,true,coalesce(nullif(p_source,''),'newsletter'),now(),null)
  on conflict(email_normalized) do update set email=excluded.email,active=true,adult_confirmed=true,source=excluded.source,consent_at=now(),unsubscribed_at=null; return true;
end; $$;

-- Los RPC de admin_store_stats, admin_customer_list y admin_customer_activity
-- se mantienen en la base productiva como interfaz privada para estadisticas.html.

revoke all on function public.record_store_event(text,text,text,text,jsonb) from public;
grant execute on function public.record_store_event(text,text,text,text,jsonb) to anon,authenticated;
revoke all on function public.set_my_profile(text,text,text,text,smallint,boolean) from public;
grant execute on function public.set_my_profile(text,text,text,text,smallint,boolean) to authenticated;
revoke all on function public.toggle_product_like(text,boolean) from public;
grant execute on function public.toggle_product_like(text,boolean) to authenticated;
revoke all on function public.subscribe_marketing(text,boolean,text) from public;
grant execute on function public.subscribe_marketing(text,boolean,text) to anon,authenticated;
